name: Terraform
description: "Action to run terraform plan and apply on STACKIT infrastructure"

inputs:
  terraform_module:
    description: "Terraform module to run terraform in"
    required: true
    default: "terraform"
  project_directory:
    description: "Name of the directory that contains the terraform module. Should end with '/'"
    required: false
    default: ""
  terraform_command:
    description: "Terraform command to run (plan/apply)"
    required: false
    default: "plan"
  STACKIT_SERVICE_ACCOUNT_KEY:
    description: "Credentials of a STACKIT Service Account Key that is used to authenticate against the STACKIT API"
    required: true
  BACKEND_ACCESS_KEY_ID:
    description: "Access Key for the terraform backend bucket"
    required: true
  BACKEND_SECRET_ACCESS_KEY:
    description: "Secret Access Key for the terraform backend bucket"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install terraform"
      uses: digitalservicebund/setup-terraform@main

    - name: "Setup STACKIT Credentials"
      env:
        STACKIT_SERVICE_ACCOUNT_KEY: ${{ inputs.STACKIT_SERVICE_ACCOUNT_KEY }}
        STACKIT_SERVICE_ACCOUNT_KEY_PATH: ${{ github.workspace }}/stackit-credentials.json
      shell: bash
      run: echo "$STACKIT_SERVICE_ACCOUNT_KEY" > $STACKIT_SERVICE_ACCOUNT_KEY_PATH

    - name: "Terraform init"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: terraform init -input=false

    - name: "Terraform plan"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: |
        terraform plan -lock=false -out .planfile

    - name: "Post PR comment"
      if: ${{ github.event_name == 'pull_request' }}
      uses: borchero/terraform-plan-comment@434458316f8f24dd073cd2561c436cce41dc8f34 # v2.4.1
      with:
        token: ${{ github.token }}
        planfile: .planfile
        header: 📝 Terraform Plan for ${{ inputs.project_directory }}${{ inputs.terraform_module }}
        working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
        skip-empty: true

    - name: "Terraform apply"
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: |
        terraform apply -auto-approve