name: Terraform
description: "Action to run terraform plan and apply on STACKIT infrastructure"

inputs:
  terraform_module:
    description: "Terraform module to run terraform in"
    required: true
    default: "terraform"
  project_directory:
    description: "Name of the directory that contains the terraform module. Should end with '/'"
    required: false
    default: ""
  STACKIT_SERVICE_ACCOUNT_KEY:
    description: "Credentials of a STACKIT Service Account Key that is used to authenticate against the STACKIT API"
    required: false
  STACKIT_SERVICE_ACCOUNT_EMAIL:
    description: "Email of a STACKIT Service Account that should be used to authenticate against the STACKIT API"
    required: false
    default: ""
  BACKEND_ACCESS_KEY_ID:
    description: "Access Key for the terraform backend bucket"
    required: true
  BACKEND_SECRET_ACCESS_KEY:
    description: "Secret Access Key for the terraform backend bucket"
    required: true

runs:
  using: "composite"
  steps:
      # Either STACKIT_SERVICE_ACCOUNT_KEY or STACKIT_SERVICE_ACCOUNT_EMAIL must be set
    - name: "Check configuration"
      shell: bash
      run: |
        if [[ -z "${{ inputs.STACKIT_SERVICE_ACCOUNT_KEY }}" && -z "${{ inputs.STACKIT_SERVICE_ACCOUNT_EMAIL }}" ]]; then
          echo "Either STACKIT_SERVICE_ACCOUNT_KEY or STACKIT_SERVICE_ACCOUNT_EMAIL must be set"
          exit 1
        fi

    - name: "Install terraform"
      uses: digitalservicebund/setup-terraform@400976bd246bef1e51fe73695fe7658ce484bc43

    - name: "Terraform init"
      if: ${{ inputs.STACKIT_SERVICE_ACCOUNT_EMAIL == '' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
        STACKIT_SERVICE_ACCOUNT_KEY: ${{ inputs.STACKIT_SERVICE_ACCOUNT_KEY }}
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: terraform init -input=false

    - name: "Terraform init"
      if: ${{ inputs.STACKIT_SERVICE_ACCOUNT_EMAIL != '' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
        STACKIT_SERVICE_ACCOUNT_EMAIL: ${{ inputs.STACKIT_SERVICE_ACCOUNT_EMAIL }}
        STACKIT_USE_OIDC: "1"
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: terraform init -input=false

    - name: "Terraform plan"
      if: ${{ github.event_name == 'pull_request' && inputs.STACKIT_SERVICE_ACCOUNT_EMAIL == '' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
        STACKIT_SERVICE_ACCOUNT_KEY: ${{ inputs.STACKIT_SERVICE_ACCOUNT_KEY }}
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: |
        terraform plan -lock=false -out .planfile

    - name: "Terraform plan"
      if: ${{ github.event_name == 'pull_request' && inputs.STACKIT_SERVICE_ACCOUNT_EMAIL != '' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
        STACKIT_SERVICE_ACCOUNT_EMAIL: ${{ inputs.STACKIT_SERVICE_ACCOUNT_EMAIL }}
        STACKIT_USE_OIDC: "1"
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: |
        terraform plan -lock=false -out .planfile

    - name: "Post PR comment"
      if: ${{ github.event_name == 'pull_request' }}
      uses: borchero/terraform-plan-comment@d177dfb833ccfb6ef6022700796190dfe54830f1 # v3.0.0
      with:
        token: ${{ github.token }}
        planfile: .planfile
        header: 📝 Terraform Plan for ${{ inputs.project_directory }}${{ inputs.terraform_module }}
        working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
        skip-empty: true

    - name: "Prevent merge if files are recreated by terraform"
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        if terraform show -no-color .planfile | grep -Fq "# DO NOT EDIT MANUALLY"; then
          echo "❌ The Terraform plan contains resources marked with '# DO NOT EDIT MANUALLY'. This configuration must be executed locally."
          exit 1
        fi

    - name: "Terraform apply"
      if: ${{ github.ref == 'refs/heads/main' && inputs.STACKIT_SERVICE_ACCOUNT_EMAIL == ''}}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
        STACKIT_SERVICE_ACCOUNT_KEY: ${{ inputs.STACKIT_SERVICE_ACCOUNT_KEY }}
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: |
        terraform apply -auto-approve

    - name: "Terraform apply"
      if: ${{ github.ref == 'refs/heads/main' && inputs.STACKIT_SERVICE_ACCOUNT_EMAIL != ''}}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.BACKEND_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.BACKEND_SECRET_ACCESS_KEY }}
        STACKIT_SERVICE_ACCOUNT_EMAIL: ${{ inputs.STACKIT_SERVICE_ACCOUNT_EMAIL }}
        STACKIT_USE_OIDC: "1"
      working-directory: ${{ inputs.project_directory }}${{ inputs.terraform_module }}
      shell: bash
      run: |
        terraform apply -auto-approve
